---
- name: Check which version of geoipupdate is installed
  block:

    - name: Check which version of geoipupdate is installed
      command: geoipupdate -V
      register: geoipupdate_version_check

    - name: Set a fact for the installed version of geoipupdate
      set_fact:
        geoipupdate_installed: "{{ geoipupdate_version_check.stderr.split(' ')[1] }}"

  tags:
    - geoipupdate
...
