---
- name: Download and install latest version of geoipupdate
  block:

    - name: Download checksums
      get_url:
        url: "https://github.com/maxmind/geoipupdate/releases/download/v{{ geoipupdate_latest }}/checksums-dpkg-rpm.txt"
        dest: "/usr/local/src/geoipupdate_{{ geoipupdate_latest }}_checksums-dpkg-rpm.txt"

    - name: Slurp checksums
      slurp:
        src: "/usr/local/src/geoipupdate_{{ geoipupdate_latest }}_checksums-dpkg-rpm.txt"
      register: geoipupdate_checksums_b64encoded

    - name: Set an array for the lines of the checksum file
      set_fact:
        geoipupdate_checksums: "{{ ( geoipupdate_checksums_b64encoded['content'] | b64decode | trim ).split('\n') }}"

    - name: Set a fact for the checksum for the deb
      set_fact:
        geoipupdate_checksum: "{{ line.split(' ')[0] }}"
      when: ( "linux_amd64.deb" in line )
      loop: "{{ geoipupdate_checksums }}"
      loop_control:
        loop_var: line
        label: "{{ line }}"

    - name: Download geoipupdate
      get_url:
        url: "https://github.com/maxmind/geoipupdate/releases/download/v{{ geoipupdate_latest }}/geoipupdate_{{ geoipupdate_latest }}_linux_amd64.deb"
        checksum: "sha256:{{ geoipupdate_checksum }}"
        dest: "/usr/local/src/geoipupdate_{{ geoipupdate_latest }}_linux_amd64.deb"

    - name: Install geoipupdate
      apt:
        deb: "/usr/local/src/geoipupdate_{{ geoipupdate_latest }}_linux_amd64.deb"

  tags:
    - geoipupdate
...
