---
- name: Check if geoipupdate is installed
  shell: which geoipupdate || echo ABSENT
  register: geoipupdate_check
  changed_when: ( "ABSENT" in geoipupdate_check.stdout )
  tags:
    - geoipupdate

- name: Check which version of geoipupdate is installed
  include_tasks: check.yml
  when: ( geoipupdate_check is defined ) and ( "geoipupdate" in geoipupdate_check.stdout )
  tags:
    - geoipupdate

- name: Check the latest version of geoipupdate
  include_tasks: latest.yml
  tags:
    - geoipupdate

- name: Download and install latest version of geoipupdate
  include_tasks: install.yml
  when: ( geoipupdate_check.stdout == "ABSENT" ) or ( geoipupdate_installed != geoipupdate_latest )
  tags:
    - geoipupdate
...
