---
- name: Check if geoipupdate is installed
  shell: which geoipupdate || echo ABSENT
  register: geoipupdate_check
  changed_when: ( "ABSENT" in geoipupdate_check.stdout )
  tags:
    - geoipupdate

- name: Check which version of geoipupdate is installed
  include_tasks: check.yml
  when: ( geoipupdate_check is defined ) and ( "geoipupdate" in geoipupdate_check.stdout )
  tags:
    - geoipupdate

- name: Check the latest version of geoipupdate
  include_tasks: latest.yml
  tags:
    - geoipupdate

- name: Download and install latest version of geoipupdate
  include_tasks: install.yml
  when: ( geoipupdate_check.stdout == "ABSENT" ) or ( geoipupdate_installed != geoipupdate_latest )
  tags:
    - geoipupdate

- name: /etc/GeoIP.conf config file in place
  template:
    src: GeoIP.conf.j2
    dest: /etc/GeoIP.conf
  tags:
    - geoipupdate

- name: Update GeoIP database crontab in place
  cron:
    name: "Update GeoIP database"
    minute: "01"
    hour: "06"
    weekday: "1"
    job: geoipupdate
  tags:
    - geoipupdate
...
