# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects GeoIP Update Ansible role.
#
# The Webarchitects GeoIP Update Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects GeoIP Update Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects GeoIP Update Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Run which geoipupdate
      ansible.builtin.command: which geoipupdate
      check_mode: false
      changed_when: false
      register: molecule_root_which_geoipupdate

    - name: Debug which geoipupdate
      ansible.builtin.debug:
        var: molecule_root_which_geoipupdate.stdout

    - name: Run which geoipupdate -a
      ansible.builtin.command: which geoipupdate -a
      check_mode: false
      changed_when: false
      register: molecule_root_which_geoipupdate_a
      failed_when: molecule_root_which_geoipupdate_a.rc is not regex('^0|1$')

    - name: Check geoipupdate versions
      ansible.builtin.command: "{{ molecule_geoipupdate_path }} --version"
      check_mode: false
      changed_when: false
      register: molecule_geoipupdate_v
      loop: "{{ molecule_root_which_geoipupdate_a.stdout_lines }}"
      loop_control:
        loop_var: molecule_geoipupdate_path

    - name: Set facts for the geoipupdate versions
      ansible.builtin.set_fact:
        molecule_geoipupdate_root_versions: "{{ molecule_geoipupdate_v | community.general.json_query('results[].{path: molecule_geoipupdate_path, version: stdout_lines[0]}') }}"

    - name: Debug geoipupdate versions
      ansible.builtin.debug:
        var: molecule_geoipupdate_root_versions
...
